apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    name: product-service
    app: demo-abc-app

spec:
  ports:
    - port: 5000
      targetPort: 5000
  selectors:
    name: product-app-pod
    app: demo-abc-app
